"""create all tables2

Revision ID: 6c30eb77d194
Revises: 9e6d870fba56
Create Date: 2022-07-29 21:38:00.200723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c30eb77d194'
down_revision = '9e6d870fba56'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
